export enum ERROR_EXCEPTION {
  NOT_FOUND = 'NOT FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL SERVER ERROR',
  LOGIN_FAILED = 'LOGIN FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  USER_EXIST = 'USER ALREADY EXISTÏ',
}
